addpath(genpath('.'));
test_repmat_inv_sum()
test_normalization_ExprZp();
test_add_expr();
test_many_add_expr();
test_multiply_expr();
test_power_expr();
test_power_expr_simple();
test_power_expr_max();
verif_mult();
