classdef X4 < PrototypeF
    properties
    end

    methods
    
          function obj = X4()
              obj.name = 'X4';
          end
        
        
          function y = f(obj, x)
              y = x .^ 4;
          end
        
          function P = FP_unnorm(obj, W)                     
            n = size(W, 1);
            m = size(W, 2);             
            P =  ( ( ( sum(sum(W, 2), 1) * sum(sum(W, 2), 1)) .* ( sum(sum(W, 2), 1) * sum(sum(W, 2), 1))) * 0.0039062) + ...
                 ( sum(( sum(W, 2) .* ( ( W * (W')) * sum(W, 2))), 1) * 0.046875) + ...
                 ( sum(sum(( W .* ( ( W * (W')) * W)), 2), 1) * 0.023438) + ...
                 ( sum(sum(( ( ( W * (W')) * W) .* repmat(sum(W, 1), [n, 1])), 2), 1) * 0.046875) + ...
                 ( sum(sum(( sum(sum(W, 2), 1) .* ( ( W * (W')) * W)), 2), 1) * 0.09375) + ...
                 ( sum(sum(( ( sum(sum(W, 2), 1) * sum(sum(W, 2), 1)) .* ( W .* W)), 2), 1) * 0.023438) + ...
                 ( sum(sum(( ( sum(sum(W, 2), 1) * sum(sum(W, 2), 1)) .* ( W .* repmat(sum(W, 2), [1, m]))), 2), 1) * 0.023438) + ...
                 ( sum(sum(( ( sum(sum(W, 2), 1) * sum(sum(W, 2), 1)) .* ( W .* repmat(sum(W, 1), [n, 1]))), 2), 1) * 0.023437) + ...
                 ( ( sum(( sum(W, 2) .* sum(W, 2)), 1) * sum(( sum(W, 2) .* sum(W, 2)), 1)) * 0.011719) + ...
                 ( ( sum(( sum(W, 2) .* sum(W, 2)), 1) * sum(sum(( W .* W), 2), 1)) * 0.023437) + ...
                 ( ( sum(( sum(W, 2) .* sum(W, 2)), 1) * sum(sum(( W .* repmat(sum(W, 1), [n, 1])), 2), 1)) * 0.023438) + ...
                 ( ( sum(sum(( W .* W), 2), 1) * sum(sum(( W .* W), 2), 1)) * 0.011719) + ...
                 ( ( sum(sum(( W .* W), 2), 1) * sum(sum(( W .* repmat(sum(W, 1), [n, 1])), 2), 1)) * 0.023438) + ...
                 ( ( sum(sum(( W .* repmat(sum(W, 1), [n, 1])), 2), 1) * sum(sum(( W .* repmat(sum(W, 1), [n, 1])), 2), 1)) * 0.011719) + ...
                 ( sum(( sum(W, 2) .* sum(( ( W .* W) .* repmat(sum(W, 2), [1, m])), 2)), 1) * -0.046875) + ...
                 ( sum(( ( sum(W, 2) .* sum(W, 2)) .* ( sum(W, 2) .* sum(W, 2))), 1) * -0.0078125) + ...
                 ( sum(( sum(( W .* W), 2) .* sum(( W .* W), 2)), 1) * -0.023438) + ...
                 ( sum(sum(( ( W .* W) .* ( W .* W)), 2), 1) * 0.015625) + ...
                 ( sum(sum(( ( W .* repmat(sum(W, 1), [n, 1])) .* ( W .* repmat(sum(W, 1), [n, 1]))), 2), 1) * -0.046875) + ...
                 ( sum(sum(( ( W .* W) .* repmat(sum(( W .* W), 1), [n, 1])), 2), 1) * -0.023437) + ...
                 ( sum(sum(( ( W .* repmat(sum(W, 1), [n, 1])) .* repmat(( sum(W, 1) .* sum(W, 1)), [n, 1])), 2), 1) * -0.0078125);
      end
    end

end
